import type { NextPage } from 'next';
import Head from 'next/head';
import About from '@/components/About';
import Skills from '@/components/Skills';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cris</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <About/>
      <Skills/>
    </div>
  );
};

export default Home;